### ISSUE TITLE
ist auch ein Datenimport per Openimmo möglich?

### ISSUE THREAD

**Issue by skerbis** [TobiasKrais/d2u_immo#1]

**Comment by TobiasKrais** [comment]
Noch nicht, wäre aber denkbar hier ein Plugin zu programmieren.

**Comment by skerbis** [comment]
lass uns mal slacken

**Comment by TobiasKrais** [comment]
Nutz ich eigentlich nicht. Kontaktier mich am besten über meine Website: https://www.design-to-use.de/impressum/

**Comment by TobiasKrais** [comment]
Hier ein anderes Projekt mit XML Import: https://github.com/TobiasKrais/d2u_jobs/blob/master/plugins/hr4you_import/lib/hr4you.php. Das könnte als Vorlage dienen. OpenImmo ist nur ein bisschen komplexer als das dort verwendete XML.

**Comment by skerbis** [comment]
Danke, es gibt **doch** (war gut versteckt) eine apidoc von onoffice, das bekomme ich dann sicher hin.

**Comment by TobiasKrais** [comment]
Wenn du OpenImmo Dokumentation brauchst, gib Bescheid. Hab sie hier.
Ich würde mich freuen, wenn du ein fertiges Import Plugin hier auf Git zur Verfügung stellen würdest, vielleicht per pull request. Oder ich nehm dich als Mitentwickler fürs Addon auf. Mit Im- und Export wird das ein echt starkes Addon was Redaxo im Immobilienbereich pushen könnte.

**Comment by skerbis** [comment]
OnOffice nutzt leider nicht OpenImmo, ist ein eigenes Format. Wenn ich was habe, kommen wir sicher zusammen.
