### ISSUE TITLE
Mini Bug: Fehler bei Aufruf von Export (keine Immobilien vorhanden)

### ISSUE THREAD

**Issue by godsdog** [TobiasKrais/d2u_immo#3]
Kleiner Fehler: Wenn noch keine Immobilien vorhanden sind und man dann auf "Export" klickt, whoopst es:

`Error while executing statement "SELECT provider_id FROM rex_d2u_immo_export_provider WHERE online_status = 'online' ORDER BY name"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online_status' in 'where clause'`

**Comment by TobiasKrais** [comment]
Danke für die Fehlermeldung! Fehler ist mit dem Commit behoben: https://github.com/TobiasKrais/d2u_immo/commit/9338b02790a80c4a530be199895c892cd4bc1dcf

Die neue Version liegt im Redaxo Installer vor.
