### ISSUE TITLE
Beim Speichern einer Immobilie [ Unknown column 'window_advertising_status' in 'field list' ]

### ISSUE THREAD

**Issue by mnhwmd** [TobiasKrais/d2u_immo#4]
Es schien das Feld 'window_advertising_status' nicht  bei der Installation des Addons in der Tabelle rex_d2u_immo_properties angelegt zu werden.

**Comment by TobiasKrais** [comment]
Vielen Dank für deinen Fehlerreport. Das Feld wird erst beim Installieren des Plugins "window_advertising" hinzugefügt. Als Workaround kannst du das Plugin installieren und aktivieren. Oder du wendest den Bugfix vom obigen commit an. In der nächsten Version wird der Fehler behoben sein.
