### ISSUE TITLE
Notiz: Verbesserungsideen: 

### ISSUE THREAD

**Issue by skerbis** [TobiasKrais/d2u_immo#5]
Ich habe mir mal den aktuellen Stand angeschaut. Tolles AddOn. 
Wollte wissen ob es für ein aktuelles Projekt bzw. Anfrage geeignet ist. 
Leider passt es nicht, dennoch: 

Dabei kamen mir folgende Ideen. 

**Formularabarbeitung:** 
Ich finde folgende Reihenfolge besser:

Kategorien
- Erst die Abfrage ob Kauf oder Miete
- danach Vermarktungsart

Texte
- Texte erst wenn Kategoriesierung abgeschlossen 

**Ideen/ Anregungen :** 

- **Bilder:** Hier wäre das imageList-Feld von Mform ziemlich nützlich 
- **Selects:** Bei den Multiple-Selects ggf. Selectpicker oder select2 einsetzen
- Button zum Aufklappen aller Formular-Abschnitte 
- Möglichkeiten zur Einschränkung der möglichen Auswahlpunkte anbieten. 

Sollte ich mal etwas Zeit haben würde ich mich gerne um das eine oder andere nach Absprache mit Dir kümmern.

**Comment by TobiasKrais** [comment]
Danke für die Hinweise. Die Reihenfolge zu ändern sollte kein Problem sein. Auch ein Button um alles aufzuklappen.

Mform nutze ich in keinem meiner Addons und würde ich mir ungern als Abhängigkeit rein holen. Was kann das Feld denn mehr als das derzeitige?

Und wegen der selects. Was meinst du mit Selectpicker und select2? Momentan werden die select Felder von hier geholt: https://github.com/TobiasKrais/d2u_helper/blob/02c24d14fb5afeeb861c25ba83dc95272933e58a/lib/d2u_addon_backend_helper.php#L440

Auch noch eine Frage zum Einschränken der Auswahlpunkte: du meinst eine Art Standard- und Expertenansicht?

**Comment by skerbis** [comment]
Das ImageList-Feld in Mform zeigt die Bilder visuell. Denke das ist praktisch für die Redakteur:innen
![Screenshot](https://raw.githubusercontent.com/FriendsOfREDAXO/mform/assets/imglist.png)
Das widget müsste man aber wohl übertragen / migrieren.  Ich weiß nicht ob's für rex_form schon was gibt. 

Zu den Selects: Gemeint ist eine live-Search. 
Die bekommst du sehr schnell mit dem in REDAXO integrierten Selectpicker. 
https://friendsofredaxo.github.io/tricks/backend/sytling-select#select-felder-styling

Mit Einschränkungen meine ich, dass man bestimmte Auswahlmöglichkeiten reduzieren kann. 
Es kann ja sein dass die Makler z.B. nur Mitangebote haben, bestimmte Abfragen nicht wollen oder benötigen.

**Comment by TobiasKrais** [comment]
Wow, das wäre ein echter Mehrwert! Bin absolut dafür! Wie dringend brauchst du das alles? Diese Woche schaff ich es nicht und danach wollte ich Urlaub machen...

**Comment by skerbis** [comment]
Nicht dringend. Ist mir ja beim Testen aufgefallen.

**Comment by TobiasKrais** [comment]
Geht klar. Eventuell brauch ich deine Hilfe. Dann melde ich mich. Danke für die guten Tipps!
Habs auf meine ToDo Liste gesetzt.

**Comment by TobiasKrais** [comment]
Ist nun endlich Version 1.3 in Verbindung mit D2U Helper 1.13.0 behoben.
